-- Create ZK proofs table
CREATE TABLE IF NOT EXISTS zk_proofs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zk_id VARCHAR(255) UNIQUE NOT NULL,
  user_wallet VARCHAR(255) NOT NULL, -- Stellar wallet address
  proof_b64 TEXT NOT NULL, -- Proof in base64 format
  public_inputs JSONB NOT NULL, -- Array of public inputs
  threshold DECIMAL(18, 2) NOT NULL, -- Minimum XLM required (in XLM, not stroops)
  is_valid BOOLEAN NOT NULL DEFAULT false, -- Whether proof was validated locally
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP, -- Optional expiration time for the proof
  metadata JSONB -- Additional metadata (nonce, etc.)
);

CREATE INDEX IF NOT EXISTS idx_zk_id ON zk_proofs(zk_id);
CREATE INDEX IF NOT EXISTS idx_zk_user_wallet ON zk_proofs(user_wallet);
CREATE INDEX IF NOT EXISTS idx_zk_created_at ON zk_proofs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_zk_expires_at ON zk_proofs(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_zk_user_wallet_created ON zk_proofs(user_wallet, created_at DESC);

-- Add comment to table
COMMENT ON TABLE zk_proofs IS 'Stores ZK proofs generated by users to prove XLM balance without revealing the actual balance';
COMMENT ON COLUMN zk_proofs.proof_b64 IS 'ZK proof in base64 format';
COMMENT ON COLUMN zk_proofs.public_inputs IS 'Public inputs array used for proof verification';
COMMENT ON COLUMN zk_proofs.threshold IS 'Minimum XLM balance required (in XLM units)';
COMMENT ON COLUMN zk_proofs.is_valid IS 'Whether the proof was validated locally before submission';

